name: R2R
description:
  R2R is the most advanced AI retrieval system. And with R2R, getting your AI
  application started is simple.
instructions: null
changeLog:
  - date: 2025-8-12
    description: first release
links:
  - label: Documentation
    url: https://r2r-docs.sciphi.ai/documentation/overview/
  - label: Github
    url: https://github.com/SciPhi-AI/R2R
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
  - name: Berk Sümbül
    url: https://berksmbl.com
  - name: Marcio Nicolau
    url: https://github.com/marcionicolau
schema:
  type: object
  required:
    - fileServerDatabaseImage
    - fileServerDatabaseMaxConnections
    - fileServerServiceName
    - hatchetServiceName
    - hatchetPostgresImage
    - hatchetRabbitmqImage
    - hatchetMigrationImage
    - hatchetSetupConfigImage
    - hatchetEngineImage
    - hatchetDashboardImage
    - hatchetSetupTokenImage
    - unstructuredImage
    - graphClusteringImage
    - r2rImage
    - r2rDashboardImage
    - r2rDashboardEmail
    - appServiceName
  properties:
    fileServerDatabaseImage:
      type: string
      title: File Server Database Image
      default: pgvector/pgvector:pg17
    fileServerDatabaseMaxConnections:
      type: integer
      title: File Server Database Max Connections
      default: 1024
    fileServerServiceName:
      type: string
      title: File Server Service Name
      default: fs
    hatchetPostgresImage:
      type: string
      title: Hatchet Postgres Image
      default: postgres:17
    hatchetServiceName:
      type: string
      title: Hatchet Service Name
      default: hatchet
    hatchetRabbitmqImage:
      type: string
      title: Hatchet Rabbitmq Image
      default: rabbitmq:3-management
    hatchetMigrationImage:
      type: string
      title: Hatchet Migration Image
      default: ghcr.io/hatchet-dev/hatchet/hatchet-migrate:v0.70.6
    hatchetSetupConfigImage:
      type: string
      title: Hatchet Setup Config Image
      default: ghcr.io/hatchet-dev/hatchet/hatchet-admin:v0.70.6
    hatchetEngineImage:
      type: string
      title: Hatchet Engine Image
      default: ghcr.io/hatchet-dev/hatchet/hatchet-engine:v0.70.6
    hatchetDashboardImage:
      type: string
      title: Hatchet Dashboard Image
      default: ghcr.io/hatchet-dev/hatchet/hatchet-dashboard:v0.70.6
    hatchetSetupTokenImage:
      type: string
      title: Hatchet Setup Token Image
      default: ghcr.io/hatchet-dev/hatchet/hatchet-admin:v0.70.6
    unstructuredImage:
      type: string
      title: Unstructured Image
      default: ragtoriches/unst-prod:latest
    graphClusteringImage:
      type: string
      title: Graph Clustering Image
      default: ragtoriches/cluster-prod:latest
    r2rImage:
      type: string
      title: R2R Image
      default: sciphiai/r2r:3.6.5
    r2rDashboardImage:
      type: string
      title: R2R Dashboard Image
      default: sciphiai/r2r-dashboard:1.0.4
    r2rDashboardEmail:
      type: string
      title: R2R Dashboard Email
      default: admin@example.com
    appServiceName:
      type: string
      title: App Service Name
      default: r2r
benefits:
tags:
  - RAG
  - AI
  - Retrieval
